// Minimal incremental source generator. Emits an interface and a record
// into the consuming project's compilation. The output exists only
// in-memory (no `EmitCompilerGeneratedFiles` set on Producer.csproj),
// which is the failure case being investigated for cross-project
// navigation.

using Microsoft.CodeAnalysis;

namespace Generator;

[Generator]
public class GreeterGenerator : IIncrementalGenerator
{
    private const string Source = """
        // <auto-generated />
        namespace Sample.Producer.Generated;

        public interface IGreeter
        {
            string Greet(string name);
        }

        public sealed record GreetResponse(string Message);
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IGreeter.g.cs", Source);
        });
    }
}
